# install.packages("knitr")
# install.packages("rmarkdown")
# install.packages("markdown")
# install.packages("openxlsx")
# install.packages("tibble")
# install.packages("kableExtra")
# install.packages("formattable")
# install.packages("dplyr")

library(knitr)
library(rmarkdown)
library(markdown)
library(openxlsx)
library(tibble)
library(kableExtra)
# library(formattable)
library(dplyr)